# Generated by Django 4.2.4 on 2023-08-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipverse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=70)),
                ('accountNumber', models.CharField(default='', max_length=70)),
                ('status', models.CharField(default='', max_length=70)),
                ('access_token', models.CharField(default='', max_length=2048)),
                ('refresh_token', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='FromLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=70)),
                ('locationName', models.CharField(blank=True, default='', max_length=70)),
                ('fullName', models.CharField(blank=True, default='', max_length=70)),
                ('attentionName', models.CharField(blank=True, default='', max_length=70)),
                ('phone', models.CharField(blank=True, default='', max_length=70)),
                ('address', models.CharField(blank=True, default='', max_length=70)),
                ('address1', models.CharField(blank=True, default='', max_length=70)),
                ('city', models.CharField(blank=True, default='', max_length=70)),
                ('stateCode', models.CharField(blank=True, default='', max_length=10)),
                ('postalCode', models.CharField(blank=True, default='', max_length=10)),
                ('countryCode', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=70)),
                ('timezone', models.CharField(blank=True, default='', max_length=70)),
                ('selected', models.BooleanField(default=False)),
                ('residential', models.BooleanField(default=False)),
                ('returnFullName', models.CharField(blank=True, default='', max_length=70)),
                ('returnAttentionName', models.CharField(blank=True, default='', max_length=70)),
                ('returnPhone', models.CharField(blank=True, default='', max_length=70)),
                ('returnAddress', models.CharField(blank=True, default='', max_length=70)),
                ('returnAddress1', models.CharField(blank=True, default='', max_length=70)),
                ('returnCity', models.CharField(blank=True, default='', max_length=70)),
                ('returnStateCode', models.CharField(blank=True, default='', max_length=10)),
                ('returnPostalCode', models.CharField(blank=True, default='', max_length=10)),
                ('returnCountryCode', models.CharField(blank=True, default='', max_length=10)),
                ('returnEmail', models.EmailField(blank=True, default='', max_length=70)),
                ('returnTimezone', models.CharField(blank=True, default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=20)),
                ('defaultContentType', models.IntegerField(blank=True, default=0)),
                ('nonDeliveryOption', models.IntegerField(blank=True, default=0)),
                ('customDeclarations', models.IntegerField(blank=True, default=0)),
                ('signCustoms', models.CharField(blank=True, default='', max_length=70)),
                ('exemptionCode', models.IntegerField(blank=True, default=0)),
                ('isSendTracking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InviteTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('emailInviteToken', models.CharField(blank=True, max_length=70, null=True)),
                ('emailInviteDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=70)),
                ('packageName', models.CharField(default='', max_length=70)),
                ('measureUnit', models.CharField(blank=True, default='', max_length=10)),
                ('length', models.FloatField(default='0')),
                ('width', models.FloatField(default='0')),
                ('height', models.FloatField(default='0')),
                ('packageCode', models.CharField(blank=True, default='', max_length=70)),
                ('upsPackage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('newPasswordToken', models.CharField(blank=True, max_length=70, null=True)),
                ('newPasswordDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=20)),
                ('order', models.CharField(blank=True, default='', max_length=20)),
                ('accountNumber', models.CharField(blank=True, default='', max_length=30)),
                ('tracknumber', models.CharField(blank=True, default='', max_length=30)),
                ('image', models.TextField(max_length=1048576, null=True)),
                ('invoice', models.TextField(max_length=1048576, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipperLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=70)),
                ('locationName', models.CharField(blank=True, default='', max_length=70)),
                ('fullName', models.CharField(blank=True, default='', max_length=70)),
                ('attentionname', models.CharField(blank=True, default='', max_length=70)),
                ('taxidnum', models.CharField(blank=True, default='', max_length=70)),
                ('phone', models.CharField(blank=True, default='', max_length=70)),
                ('shipperno', models.CharField(blank=True, default='', max_length=70)),
                ('fax', models.CharField(blank=True, default='', max_length=70)),
                ('address', models.CharField(blank=True, default='', max_length=70)),
                ('address1', models.CharField(blank=True, default='', max_length=70)),
                ('city', models.CharField(blank=True, default='', max_length=70)),
                ('statecode', models.CharField(blank=True, default='', max_length=10)),
                ('postalcode', models.CharField(blank=True, default='', max_length=10)),
                ('countrycode', models.CharField(blank=True, default='', max_length=2)),
                ('email', models.CharField(blank=True, default='', max_length=30)),
                ('selected', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=70)),
                ('access_token', models.CharField(default='', max_length=255, null=True)),
                ('storeHash', models.CharField(default='', max_length=255, null=True)),
                ('code', models.CharField(default='', max_length=255, null=True)),
                ('accessScope', models.CharField(default='', max_length=255, null=True)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=20)),
                ('idType', models.CharField(blank=True, default=0, max_length=10)),
                ('authority', models.CharField(blank=True, default='', max_length=2)),
                ('number', models.CharField(blank=True, default='', max_length=70)),
                ('nickname', models.CharField(blank=True, default='', max_length=70)),
                ('description', models.CharField(blank=True, default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=70, unique=True)),
                ('fullName', models.CharField(blank=True, default='', max_length=70)),
                ('email', models.EmailField(blank=True, default='', max_length=70)),
                ('password', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(blank=True, default='', max_length=70)),
                ('usertype', models.CharField(blank=True, default='', max_length=70)),
                ('roles', models.CharField(default='', max_length=70)),
                ('parentuser', models.CharField(default='', max_length=70)),
                ('customerId', models.CharField(default='', max_length=70)),
                ('active', models.BooleanField(default=False)),
                ('isEmailVerified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('emailVerificationToken', models.CharField(blank=True, max_length=70, null=True)),
                ('emailVerificationDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
