# Generated by Django 4.2.2 on 2023-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='subscription_count',
            field=models.IntegerField(default=0),
        ),
    ]
