# Generated by Django 4.2.2 on 2023-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0003_users_subscription_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
