# Generated by Django 4.2.2 on 2023-08-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0004_users_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=70)),
                ('subscription_count', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, default='', max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='subscription_count',
        ),
    ]
