# Generated by Django 4.2.2 on 2023-08-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0006_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='useId',
            field=models.CharField(default='', max_length=20),
        ),
    ]
