# Generated by Django 4.2.2 on 2023-08-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0008_rename_useid_shop_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='custmer_id',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
