# Generated by Django 4.2.2 on 2023-08-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0009_subscriptions_custmer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='custmer_id',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='subscription_id',
            field=models.CharField(default='', max_length=70),
        ),
    ]
