# Generated by Django 4.2.2 on 2023-09-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0010_rename_custmer_id_subscriptions_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
