# Generated by Django 4.2.2 on 2023-09-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0011_subscriptions_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
