# Generated by Django 4.2.2 on 2023-09-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0012_subscriptions_cancel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationalsettings',
            name='customDeclarations',
        ),
        migrations.RemoveField(
            model_name='internationalsettings',
            name='exemptionCode',
        ),
        migrations.RemoveField(
            model_name='internationalsettings',
            name='isSendTracking',
        ),
        migrations.RemoveField(
            model_name='internationalsettings',
            name='nonDeliveryOption',
        ),
        migrations.RemoveField(
            model_name='internationalsettings',
            name='signCustoms',
        ),
        migrations.AddField(
            model_name='internationalsettings',
            name='declarationStatement',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='internationalsettings',
            name='termsOfSale',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='internationalsettings',
            name='defaultContentType',
            field=models.CharField(blank=True, default=''),
        ),
    ]
