# Generated by Django 4.2.2 on 2023-09-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0014_rename_tracknumber_shipment_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='trackingurl',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
