# Generated by Django 4.2.2 on 2023-10-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0015_alter_shipment_trackingurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
