# Generated by Django 4.2.2 on 2023-11-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0016_users_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=500),
        ),
    ]
