# Generated by Django 4.2.7 on 2023-11-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0018_users_ups_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_ups_details',
            old_name='counrty',
            new_name='counrty2',
        ),
        migrations.RenameField(
            model_name='users_ups_details',
            old_name='country',
            new_name='country1',
        ),
    ]
