# Generated by Django 4.2.7 on 2023-12-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0021_rename_fullname_users_ups_details_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=20)),
                ('fullName', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('street1', models.CharField(max_length=250)),
                ('street2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('country1', models.CharField(max_length=250)),
                ('zip_code', models.IntegerField()),
                ('account_number', models.CharField(max_length=250)),
                ('account_nickname', models.CharField(blank=True, max_length=250, null=True)),
                ('counrty', models.CharField(max_length=20)),
                ('postcode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipverse.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Users_UPS_details',
        ),
    ]
