# Generated by Django 4.2.7 on 2023-12-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0022_usercarrier_delete_users_ups_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercarrier',
            old_name='counrty',
            new_name='country',
        ),
    ]
