# Generated by Django 4.2.7 on 2023-12-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0025_alter_users_customerid_alter_users_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandapostUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=250, null=True)),
                ('contact_number', models.CharField(max_length=250, null=True)),
                ('merchant_username', models.CharField(max_length=250, null=True)),
                ('merchant_password', models.CharField(max_length=250, null=True)),
                ('has_credit_card', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
