# Generated by Django 4.2.7 on 2023-12-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0026_candapostuserdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candapostuserdetails',
            old_name='contact_number',
            new_name='contract_number',
        ),
    ]
