# Generated by Django 4.2.7 on 2023-12-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0028_alter_usercarrier_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercarrier',
            name='phone',
            field=models.CharField(),
        ),
    ]
