# Generated by Django 4.2.7 on 2023-12-13 16:10

from django.db import migrations, models
import django.db.models.deletion
import shipverse.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0029_alter_usercarrier_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candapostuserdetails',
            name='user',
            field=models.ForeignKey(default=shipverse.models.Users, on_delete=django.db.models.deletion.CASCADE, to='shipverse.users'),
        ),
    ]
