# Generated by Django 4.2.7 on 2023-12-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipverse', '0030_candapostuserdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candapostuserdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipverse.users'),
        ),
    ]
